name: Test con Selenium

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Chrome 114
      run: |
        wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.0_amd64.deb
        sudo dpkg -i google-chrome-stable_114.0.0_amd64.deb
        sudo apt-get install -f

    - name: Install Chrome WebDriver 114
      run: |
        wget https://chromedriver.storage.googleapis.com/114.0.0/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2

      with:
        node-version: '20'

    - name: Instalar dependencias
      run: npm install

    - name: Run selenium tests
      run: npm run test