name: Test con Selenium

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v2

    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2

      with:
        node-version: '20'

    - name: Instalar dependencias
      run: npm install

    - name: Run selenium tests
      run: npm run test